//
//  MarkdownGeneratorV3.swift
//  DayArc
//
//  Clean modular i18n generator with block toggles.
//

import Foundation

struct MarkdownGeneratorV3 {
    struct LangStrings {
        let language: ReportLanguage
        enum Key {
            case startRoutine, todo, focusBlocks, emotion, insights, recap
            case dayflow, highlights, stats, history, aiAnalysis
            case topApps, timeline, charts, scorecard, recommendations, generatedBy
            case dailyBreakdown, weeklySummary, monthlySummary, categoryBreakdown, appBreakdown, patterns
        }
        func t(_ key: Key) -> String {
            switch (language, key) {
            case (.english, .startRoutine): return "Start Routine"
            case (.english, .todo): return "TODO"
            case (.english, .focusBlocks): return "Focus Blocks"
            case (.english, .emotion): return "Emotion & Flow"
            case (.english, .insights): return "Insights"
            case (.english, .recap): return "One-line Recap"
            case (.english, .dayflow): return "Dayflow Auto Analysis"
            case (.english, .highlights): return "Key Highlights"
            case (.english, .stats): return "Statistics"
            case (.english, .history): return "History / Delta"
            case (.english, .aiAnalysis): return "AI Analysis"
            case (.english, .topApps): return "Top Applications"
            case (.english, .timeline): return "Activity Timeline"
            case (.english, .charts): return "Charts"
            case (.english, .scorecard): return "Feature Utility Scorecard"
            case (.english, .recommendations): return "Recommendations"
            case (.english, .generatedBy): return "Generated by DayArc on"
            case (.english, .dailyBreakdown): return "Daily Breakdown"
            case (.english, .weeklySummary): return "Weekly Summary"
            case (.english, .monthlySummary): return "Monthly Summary"
            case (.english, .categoryBreakdown): return "Category Breakdown"
            case (.english, .appBreakdown): return "App Usage"
            case (.english, .patterns): return "Patterns"
            case (.korean, .startRoutine): return "시작 루틴"
            case (.korean, .todo): return "TODO"
            case (.korean, .focusBlocks): return "집중 블록"
            case (.korean, .emotion): return "감정 & 몰입"
            case (.korean, .insights): return "오늘의 통찰"
            case (.korean, .recap): return "한 줄 회고"
            case (.korean, .dayflow): return "Dayflow 자동 분석"
            case (.korean, .highlights): return "오늘의 핵심 하이라이트"
            case (.korean, .stats): return "통계"
            case (.korean, .history): return "히스토리 / 델타"
            case (.korean, .aiAnalysis): return "AI 분석"
            case (.korean, .topApps): return "상위 앱"
            case (.korean, .timeline): return "활동 타임라인"
            case (.korean, .charts): return "차트"
            case (.korean, .scorecard): return "기능 유틸리티 점수표"
            case (.korean, .recommendations): return "추천/액션아이템"
            case (.korean, .generatedBy): return "Generated by DayArc on"
            case (.korean, .dailyBreakdown): return "일별 생산성"
            case (.korean, .weeklySummary): return "주간 요약"
            case (.korean, .monthlySummary): return "월간 요약"
            case (.korean, .categoryBreakdown): return "카테고리별 분배"
            case (.korean, .appBreakdown): return "앱 사용"
            case (.korean, .patterns): return "패턴"
            }
        }
    }

    // MARK: Helpers
    private static func ratingBar(_ score: Double) -> String {
        let filled = Int((score / 100) * 10)
        let empty = 10 - filled
        return String(repeating: "█", count: filled) + String(repeating: "░", count: empty)
    }

    private static func scoreGrade(_ score: Double) -> String {
        switch score {
        case 90...100: return "S"
        case 80..<90: return "A"
        case 70..<80: return "B"
        case 60..<70: return "C"
        case 50..<60: return "D"
        default: return "F"
        }
    }

    static func deltaString(_ current: Double, _ baseline: Double) -> String {
        let d = current - baseline
        if d > 0 { return "▲ " + String(format: "%.1f", d) }
        if d < 0 { return "▼ " + String(format: "%.1f", abs(d)) }
        return "—"
    }

    // MARK: Daily
    static func daily(date: Date, stats: DailyStats, analysis: AnalysisResult?, activities: [TimelineCard], history: MarkdownGenerator.HistoricalContext?, chartPaths: [URL], language: ReportLanguage, blocks: ReportBlocks, timelineSummaries: [TimelineSummary] = []) -> String {
        let s = LangStrings(language: language)
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        let dateString = fmt.string(from: date)
        // Note: fullDate can be used if needed for expanded date display
        // fmt.dateFormat = language == .korean ? "yyyy년 M월 d일 EEEE" : "EEEE, MMMM d, yyyy"
        // let fullDate = fmt.string(from: date)
        let timeFmt = DateFormatter()
        timeFmt.dateFormat = language == .korean ? "a h:mm" : "h:mm a"

        // Conditional calculation: only compute analyses when needed
        let needsDeepWork = blocks.includeStats || blocks.includeDeepWorkAnalysis || blocks.includeRecommendations || blocks.includeScorecard
        let needsDistraction = blocks.includeStats || blocks.includeDistractionBreakdown || blocks.includeRecommendations || blocks.includeScorecard
        let needsContext = blocks.includeStats || blocks.includeContextSwitching || blocks.includeRecommendations || blocks.includeScorecard
        let deepWorkAnalysis: DeepWorkAnalysis? = needsDeepWork ? StatsCalculator.calculateDeepWorkAnalysis(from: activities, thresholdMinutes: 25) : nil
        let distractionAnalysis: DistractionAnalysis? = needsDistraction ? StatsCalculator.calculateDistractionAnalysis(from: activities) : nil
        let contextAnalysis: ContextSwitchingAnalysis? = needsContext ? StatsCalculator.calculateContextSwitchingAnalysis(from: activities) : nil
        // Note: focusBlocks can be generated on-demand if needed in the future
        // let focusBlocks = blocks.includeFocusBlocks ? StatsCalculator.generateFocusBlocks(from: activities, minimumMinutes: 30) : []

        // Calculate key highlights
        let longestSession = activities.max(by: { $0.duration < $1.duration })
        let deepWorkHours = deepWorkAnalysis?.totalDeepWorkTime ?? 0
        let deepWorkPercent = stats.totalActiveTime > 0 ? (deepWorkHours * 3600 / stats.totalActiveTime * 100) : 0
        let deepWorkTarget = 40.0
        let deepWorkGap = deepWorkPercent - deepWorkTarget

        // Productivity status
        let productivityStatus = stats.productivityScore.totalScore >= 70 ? "우수 ✨" : stats.productivityScore.totalScore >= 50 ? "양호 ✅" : "개선 필요 ⚠️"

        var md = "# ✅ Daily Note - \(dateString)\n\n"

        if blocks.includeStartRoutine {
            md += "## \(s.t(.startRoutine))\n\n"
            md += "- [ ] 기상 시간:\n"
            md += "- [ ] 수면 시간:\n"
            md += "- [ ] 컨디션 (1~10):\n\n"
        }

        if blocks.includeTodo {
            md += "## \(s.t(.todo))\n\n"
            md += "- [ ]\n"
            md += "- [ ]\n"
            md += "- [ ]\n\n"
        }

        if blocks.includeFocusBlocks {
            md += "## \(s.t(.focusBlocks))\n\n"
            md += "|시간|활동|집중도|방해요소|개선점|\n"
            md += "|---|---|---|---|---|\n"
            md += "|||||\n\n"
        }

        if blocks.includeEmotion {
            md += "## \(s.t(.emotion))\n\n"
            md += "- 감정 점수:\n"
            md += "- 잘한 것 & 좋았던 것:\n"
            md += "- 못한 것 & 안좋았던 것:\n\n"
        }

        if blocks.includeInsights {
            md += "## \(s.t(.insights))\n\n"
            md += ">\n\n"
        }

        if blocks.includeRecap {
            md += "## \(s.t(.recap))\n\n"
            md += ">\n\n"
        }

        md += "\n\n---\n\n"

        // Dayflow Auto Analysis Header - show if any analysis section is enabled
        let hasAnalysisSections = blocks.includeStats || blocks.includeTimeline || blocks.includeCategoriesAndApps ||
                                  blocks.includeCharts || blocks.includeDeepWorkAnalysis || blocks.includeDistractionBreakdown ||
                                  blocks.includeContextSwitching || blocks.includeRecommendations || blocks.includeScorecard
        if hasAnalysisSections {
             md += "# 📊 \(s.t(.dayflow))\n\n"
        }

        if blocks.includeStats {
            // Safely unwrap optional analyses (they will exist because needsDeepWork/needsDistraction/needsContext are true when includeStats is true)
            let distraction = distractionAnalysis ?? DistractionAnalysis(distractingAppTime: 0, interruptionCount: 0, shortSessionCount: 0, hourlyDistractionCount: [:], peakDistractionHours: nil)
            let context = contextAnalysis ?? ContextSwitchingAnalysis(totalSwitches: 0, averageSessionLength: 0, flowSessions: [], frequentSwitchPatterns: [])

            md += "## ⭐ \(s.t(.highlights))\n\n"
            md += "1. 🔥 **\(longestSession?.appName ?? "활동 없음")** (\(Int((longestSession?.duration ?? 0) / 60))분) - 최장 집중 작업\n"
            md += "2. 🟠 **생산성 \(String(format: "%.1f", stats.productivityScore.totalScore))점** - \(productivityStatus)\n"
            md += "3. ⚠️ **Deep Work \(String(format: "%.1f", deepWorkHours))시간 (\(Int(deepWorkPercent))%)** - 목표까지 \(abs(Int(deepWorkGap)))% \(deepWorkGap >= 0 ? "초과" : "부족")\n\n"
            md += "---\n\n"

            md += "## 📈 \(s.t(.stats))\n\n"
            md += "- **총 업무 시간**: \(String(format: "%.1f", stats.totalActiveTime / 3600))시간 (\(Int(stats.totalActiveTime / 60))분)\n"
            md += "- **집중 작업 시간 (Deep Work)**: \(String(format: "%.1f", deepWorkHours))시간 (\(Int(deepWorkHours * 60))분)\n"
            md += "- **생산성 점수**: \(String(format: "%.1f", stats.productivityScore.totalScore))/100\n"
            md += "- **주요 활동**: \(activities.first?.appName ?? "없음")\n"
            md += "- **방해 앱 세션**: \(distraction.interruptionCount)회\n\n"

            md += "### 🔍 생산성 점수 분석\n\n"
            md += "**총점: \(String(format: "%.1f", stats.productivityScore.totalScore))/100**\n\n"

            md += "- **집중 작업 (Deep Work)**: \(String(format: "%.1f", stats.productivityScore.deepWorkScore))/100 (가중치 45%)\n"
            md += "  - 📊 Deep Work 비율: \(Int(deepWorkPercent))% - \(String(format: "%.1f", deepWorkHours))시간 / \(String(format: "%.1f", stats.totalActiveTime / 3600))시간\n\n"

            md += "- **집중도 (방해 없음)**: \(String(format: "%.1f", max(0, 100 - stats.productivityScore.distractionScore)))/100 (가중치 30%)\n"
            md += "  - 📊 방해 앱 세션: \(distraction.interruptionCount)회, 짧은 세션: \(distraction.shortSessionCount)회\n\n"

            md += "- **업무 균형**: \(String(format: "%.1f", stats.productivityScore.diversityScore))/100 (가중치 15%)\n"
            md += "  - 📊 앱 다양성: \(stats.uniqueApps)개 앱 사용 (2-3개 최적)\n\n"

            md += "- **업무 일관성**: \(String(format: "%.1f", stats.productivityScore.consistencyScore))/100 (가중치 10%)\n"
            md += "  - 📊 평균 세션 길이: \(String(format: "%.0f", context.averageSessionLength))분/블록\n\n"

            md += "**💡 개선 제안:**\n\n"
            md += "- 💡 **Deep Work 시간 늘리기**: 25분 이상 집중 작업 세션을 더 많이 만들어보세요. 현재 \(Int(deepWorkPercent))%, 목표 40%+\n\n"
            md += "- 💡 **작업 블록 늘리기**: 평균 작업 시간이 \(String(format: "%.0f", context.averageSessionLength))분입니다. 30-60분 단위로 작업을 계획해보세요.\n\n"
        }

        // Deep Work Analysis Section
        if blocks.includeDeepWorkAnalysis, let deepWork = deepWorkAnalysis {
            // Calculate derived metrics from DeepWorkAnalysis
            let sessionCount = deepWork.sessions.count
            let avgSessionLength = sessionCount > 0 ? (deepWork.totalDeepWorkTime * 60) / Double(sessionCount) : 0
            let longestSessionDW = deepWork.sessions.map { $0.duration / 60 }.max() ?? 0  // duration is in seconds

            md += "\n## 🎯 Deep Work 분석\n\n"
            md += "| 지표 | 값 | 설명 |\n"
            md += "|------|-----|------|\n"
            md += "| 총 Deep Work 시간 | \(String(format: "%.1f", deepWork.totalDeepWorkTime))시간 | 25분 이상 집중 작업 |\n"
            md += "| Deep Work 비율 | \(Int(deepWorkPercent))% | 전체 업무 시간 대비 |\n"
            md += "| Deep Work 세션 수 | \(sessionCount)회 | 25분+ 집중 블록 |\n"
            md += "| 평균 Deep Work 길이 | \(String(format: "%.0f", avgSessionLength))분 | 세션당 평균 |\n"
            md += "| 최장 Deep Work | \(String(format: "%.0f", longestSessionDW))분 | 가장 긴 집중 시간 |\n\n"

            if deepWorkPercent < 40 {
                md += "💡 **개선 제안**: Deep Work 비율이 \(Int(deepWorkPercent))%입니다. 목표 40% 달성을 위해 방해 요소를 줄이고 집중 블록을 늘려보세요.\n\n"
            } else {
                md += "✅ **좋은 성과**: Deep Work 비율 \(Int(deepWorkPercent))%로 목표(40%)를 달성했습니다!\n\n"
            }
        }

        // Distraction Breakdown Section
        if blocks.includeDistractionBreakdown, let distraction = distractionAnalysis {
            // Calculate derived metrics from DistractionAnalysis
            let distractionTimeRatio = stats.totalActiveTime > 0 ? (distraction.distractingAppTime * 3600 / stats.totalActiveTime) : 0
            let totalDistractionMinutes = distraction.distractingAppTime * 60

            md += "\n## ⚡ 방해 요소 분석\n\n"
            md += "| 지표 | 값 | 영향 |\n"
            md += "|------|-----|------|\n"
            md += "| 방해 앱 세션 | \(distraction.interruptionCount)회 | 집중 흐름 중단 |\n"
            md += "| 짧은 세션 (5분 미만) | \(distraction.shortSessionCount)회 | 얕은 작업 |\n"
            md += "| 방해 앱 시간 | \(String(format: "%.0f", totalDistractionMinutes))분 | 비생산적 시간 |\n"
            md += "| 방해 시간 비율 | \(String(format: "%.1f", distractionTimeRatio * 100))% | 전체 대비 |\n\n"

            // Peak distraction hours
            if let peakHours = distraction.peakDistractionHours {
                md += "### ⏰ 방해가 잦은 시간대\n\n"
                md += "**\(peakHours.start):00 ~ \(peakHours.end):00** 사이에 방해가 가장 많았습니다 (\(peakHours.count)회)\n\n"
            }

            if distraction.interruptionCount > 10 {
                md += "⚠️ **주의**: 방해 세션이 \(distraction.interruptionCount)회로 많습니다. 알림 설정을 검토하고 집중 모드 사용을 고려해보세요.\n\n"
            }
        }

        // Context Switching Analysis Section
        if blocks.includeContextSwitching, let context = contextAnalysis {
            // Calculate derived metrics from ContextSwitchingAnalysis
            let activeHours = stats.totalActiveTime / 3600
            let switchesPerHour = activeHours > 0 ? Double(context.totalSwitches) / activeHours : 0
            let longestContinuousWork = context.flowSessions.map { $0.duration * 60 }.max() ?? 0  // duration is in hours, convert to minutes

            md += "\n## 🔄 컨텍스트 전환 분석\n\n"
            md += "| 지표 | 값 | 의미 |\n"
            md += "|------|-----|------|\n"
            md += "| 총 전환 횟수 | \(context.totalSwitches)회 | 앱/작업 간 전환 |\n"
            md += "| 시간당 전환 | \(String(format: "%.1f", switchesPerHour))회 | 집중도 지표 |\n"
            md += "| 평균 세션 길이 | \(String(format: "%.0f", context.averageSessionLength))분 | 작업당 평균 시간 |\n"
            md += "| 가장 긴 연속 작업 | \(String(format: "%.0f", longestContinuousWork))분 | 최대 집중 시간 |\n\n"

            let switchLevel: String
            if switchesPerHour < 4 {
                switchLevel = "✅ **우수**: 시간당 전환이 적어 집중도가 높습니다."
            } else if switchesPerHour < 8 {
                switchLevel = "⚠️ **보통**: 전환 빈도가 약간 높습니다. 작업 블록을 더 길게 유지해보세요."
            } else {
                switchLevel = "🔴 **주의**: 전환이 매우 잦습니다. 멀티태스킹을 줄이고 단일 작업에 집중해보세요."
            }
            md += "\(switchLevel)\n\n"
        }

        // Recommendations Section
        if blocks.includeRecommendations {
            // Safely unwrap optional analyses
            let distraction = distractionAnalysis ?? DistractionAnalysis(distractingAppTime: 0, interruptionCount: 0, shortSessionCount: 0, hourlyDistractionCount: [:], peakDistractionHours: nil)
            let context = contextAnalysis ?? ContextSwitchingAnalysis(totalSwitches: 0, averageSessionLength: 0, flowSessions: [], frequentSwitchPatterns: [])

            md += "\n## 💪 실행 가능한 추천\n\n"

            // Calculate metrics for recommendations
            let activeHoursForRecs = stats.totalActiveTime / 3600
            let switchesPerHourForRecs = activeHoursForRecs > 0 ? Double(context.totalSwitches) / activeHoursForRecs : 0

            var recommendations: [String] = []

            // Deep Work recommendations
            if deepWorkPercent < 40 {
                recommendations.append("🎯 **Deep Work 늘리기**: 25분 이상 집중 작업 세션을 더 만들어보세요. 현재 \(Int(deepWorkPercent))%, 목표 40%+")
            }

            // Distraction recommendations
            if distraction.interruptionCount > 10 {
                recommendations.append("🔕 **알림 관리**: 방해 앱 알림을 끄고 집중 모드를 활성화해보세요. 현재 \(distraction.interruptionCount)회 중단")
            }

            // Context switching recommendations
            if switchesPerHourForRecs > 8 {
                recommendations.append("⏱️ **작업 블록화**: 30-60분 단위로 작업을 계획하고 타이머를 사용해보세요. 현재 시간당 \(String(format: "%.1f", switchesPerHourForRecs))회 전환")
            }

            // Session length recommendations
            if context.averageSessionLength < 15 {
                recommendations.append("📊 **세션 연장**: 평균 세션이 \(String(format: "%.0f", context.averageSessionLength))분으로 짧습니다. 작업 시작 전 명확한 목표를 설정해보세요.")
            }

            // Productivity score recommendations
            if stats.productivityScore.totalScore < 50 {
                recommendations.append("📈 **생산성 개선**: 생산성 점수가 \(String(format: "%.0f", stats.productivityScore.totalScore))점입니다. 가장 중요한 작업을 오전에 배치해보세요.")
            }

            if recommendations.isEmpty {
                md += "🎉 **훌륭합니다!** 오늘의 작업 패턴이 전반적으로 좋습니다. 이 리듬을 유지하세요!\n\n"
            } else {
                for (idx, rec) in recommendations.enumerated() {
                    md += "\(idx + 1). \(rec)\n\n"
                }
            }
        }

        // Scorecard Section
        if blocks.includeScorecard {
            // Safely unwrap optional analyses
            let distraction = distractionAnalysis ?? DistractionAnalysis(distractingAppTime: 0, interruptionCount: 0, shortSessionCount: 0, hourlyDistractionCount: [:], peakDistractionHours: nil)
            let context = contextAnalysis ?? ContextSwitchingAnalysis(totalSwitches: 0, averageSessionLength: 0, flowSessions: [], frequentSwitchPatterns: [])

            md += "\n## 📋 생산성 스코어카드\n\n"

            // Calculate individual scores for scorecard
            let deepWorkScore = min(100, deepWorkPercent * 2.5)  // 40% = 100점
            let focusScore = max(0, 100 - Double(distraction.interruptionCount) * 5)
            let consistencyScore = min(100, context.averageSessionLength * 3.33)  // 30분 = 100점
            let balanceScore = stats.productivityScore.diversityScore

            md += "| 항목 | 점수 | 바 | 등급 |\n"
            md += "|------|------|-----|------|\n"
            md += "| 🎯 Deep Work | \(Int(deepWorkScore))/100 | \(ratingBar(deepWorkScore)) | \(scoreGrade(deepWorkScore)) |\n"
            md += "| 🔕 집중도 | \(Int(focusScore))/100 | \(ratingBar(focusScore)) | \(scoreGrade(focusScore)) |\n"
            md += "| ⏱️ 일관성 | \(Int(consistencyScore))/100 | \(ratingBar(consistencyScore)) | \(scoreGrade(consistencyScore)) |\n"
            md += "| ⚖️ 균형 | \(Int(balanceScore))/100 | \(ratingBar(balanceScore)) | \(scoreGrade(balanceScore)) |\n"
            md += "| **📊 종합** | **\(Int(stats.productivityScore.totalScore))/100** | **\(ratingBar(stats.productivityScore.totalScore))** | **\(scoreGrade(stats.productivityScore.totalScore))** |\n\n"

            // Overall assessment
            let overallAssessment: String
            if stats.productivityScore.totalScore >= 80 {
                overallAssessment = "🏆 **탁월한 하루**였습니다! 이 패턴을 유지하세요."
            } else if stats.productivityScore.totalScore >= 60 {
                overallAssessment = "✅ **좋은 하루**였습니다. 약간의 개선으로 더 나아질 수 있습니다."
            } else if stats.productivityScore.totalScore >= 40 {
                overallAssessment = "⚠️ **보통의 하루**였습니다. 집중 시간을 늘려보세요."
            } else {
                overallAssessment = "🔴 **개선이 필요한 하루**입니다. 방해 요소를 줄이고 계획을 세워보세요."
            }
            md += overallAssessment + "\n\n"
        }

        // Only append timeline if requested
        if blocks.includeTimeline {
             md += "\n## 🎯 \(s.t(.timeline))\n"
            // Group activities by similar time periods and preserve full TimelineCard data
            struct ActivityGroup {
                var startTime: Date
                var endTime: Date
                var activities: [TimelineCard]
                var duration: Double
            }

            var activityGroups: [ActivityGroup] = []

            // Group consecutive activities within 5 minutes
            for activity in activities.sorted(by: { $0.startAt < $1.startAt }) {
                if let lastGroupIndex = activityGroups.indices.last,
                   activity.startAt.timeIntervalSince(activityGroups[lastGroupIndex].endTime) < 300 {
                    // Extend the last group
                    activityGroups[lastGroupIndex].endTime = activity.startAt.addingTimeInterval(activity.duration)
                    activityGroups[lastGroupIndex].activities.append(activity)
                    activityGroups[lastGroupIndex].duration += activity.duration
                } else {
                    // Start a new group
                    activityGroups.append(ActivityGroup(
                        startTime: activity.startAt,
                        endTime: activity.startAt.addingTimeInterval(activity.duration),
                        activities: [activity],
                        duration: activity.duration
                    ))
                }
            }

            // Generate timeline entries with detailed activity information from Dayflow SQLite
            for (index, group) in activityGroups.prefix(10).enumerated() {
                let startTimeStr = timeFmt.string(from: group.startTime)
                let endTimeStr = timeFmt.string(from: group.endTime)
                let durationMin = Int(group.duration / 60)

                // Extract unique apps
                let apps = Array(Set(group.activities.map { $0.appName }))

                // Use AI-generated summary if available
                if index < timelineSummaries.count {
                    let summary = timelineSummaries[index]

                    // Add category if available
                    let categoryInfo = summary.category.map { " | \($0)" } ?? ""

                    md += "\n### \(startTimeStr) - \(endTimeStr)\(categoryInfo)\n\n"
                    md += "**\(summary.title)**\n\n"
                    md += "\(summary.summary)\n\n"
                    md += "---\n\n"
                } else {
                    // Fallback: use raw data
                    md += "\n### \(startTimeStr) - \(endTimeStr) (\(durationMin)분)\n\n"
                    md += "**사용 도구:** \(apps.joined(separator: ", "))\n\n"
                    md += "**활동 내용:**\n\n"

                    // Collect all summaries and detailed info from the group
                    var contentParts: [String] = []

                    for activity in group.activities {
                        let activityDurationMin = Int(activity.duration / 60)
                        let activityTime = timeFmt.string(from: activity.startAt)

                        // Use detailed_summary if available, fallback to summary, then windowTitle
                        if let detailedSummary = activity.detailedSummary, !detailedSummary.isEmpty {
                            contentParts.append("[\(activityTime), \(activityDurationMin)분] \(activity.appName): \(detailedSummary)")
                        } else if let summary = activity.summary, !summary.isEmpty {
                            contentParts.append("[\(activityTime), \(activityDurationMin)분] \(activity.appName): \(summary)")
                        } else if let windowTitle = activity.windowTitle, !windowTitle.isEmpty {
                            var part = "[\(activityTime), \(activityDurationMin)분] \(activity.appName): \(windowTitle)"
                            if let url = activity.url, !url.isEmpty {
                                part += " (\(url))"
                            }
                            contentParts.append(part)
                        } else {
                            contentParts.append("[\(activityTime), \(activityDurationMin)분] \(activity.appName)")
                        }
                    }

                    // Combine all content
                    let fullContent = contentParts.joined(separator: "\n\n")

                    md += "\(fullContent)\n\n"
                    md += "---\n\n"
                }
            }
        }

        // AI Insights Section
        if blocks.includeAISection {
             // Only show AI section if requested
             if let analysis = analysis {
                 Logger.shared.debug("🎨 Markdown: Adding AI insights section", source: "MarkdownGen")
                 Logger.shared.debug("🎨 Markdown: Summary='\(analysis.summary.prefix(50))', Insights=\(analysis.insights.count), Recs=\(analysis.recommendations.count)", source: "MarkdownGen")

                 let insightsText = analysis.insights.map { "- " + $0 }.joined(separator: "\n")
                 let recsText = analysis.recommendations.map { "- " + $0 }.joined(separator: "\n")

                 Logger.shared.debug("🎨 Markdown: Insights text length: \(insightsText.count), Recs text length: \(recsText.count)", source: "MarkdownGen")

                 md += "\n## 💡 AI 인사이트\n\n"
                 md += "### 📝 요약\n"
                 md += "\(analysis.summary)\n\n"
                 md += "### 🔍 핵심 인사이트\n"
                 md += "\(insightsText)\n\n"
                 md += "### 💪 실행 가능한 제안\n"
                 md += "\(recsText)\n\n"
                 md += "*Generated by \(analysis.provider) (\(analysis.model))*\n\n"

                 Logger.shared.debug("🎨 Markdown: AI section added to markdown. Current md length: \(md.count)", source: "MarkdownGen")
             } else {
                 Logger.shared.error("🎨 Markdown: Analysis is nil! No AI insights section added", source: "MarkdownGen")
             }
        }

        // Category breakdown - use app names as categories for simplicity
        if blocks.includeCategoriesAndApps {
            md += "\n## 📂 카테고리별 시간 분배\n\n"
            md += "| 카테고리 | 시간 | 비율 |\n"
            md += "|---------|------|------|\n\n"

            for app in stats.topApps.prefix(5) {
                md += "| \(app.appName) | \(String(format: "%.1f", app.duration / 3600))h | \(String(format: "%.1f", app.percentage))% |\n"
            }
            md += "\n"
        }

        // App usage statistics
        if blocks.includeCategoriesAndApps {
            md += "\n## 📱 앱 사용 통계\n\n"
            md += "| 앱/도구 | 사용 시간 |\n"
            md += "|---------|----------|\n\n"

            for app in stats.topApps.prefix(10) {
                md += "| \(app.appName) | \(String(format: "%.1f", app.duration / 3600))h |\n"
            }
            md += "\n"
        }

        // Charts section - only if charts are available
        if blocks.includeCharts && !chartPaths.isEmpty {
            md += "\n\n## 📈 시각화\n\n"

            for chartPath in chartPaths {
                let fileName = chartPath.lastPathComponent
                md += "### \(fileName)\n"
                md += "![[charts/\(fileName)]]\n\n"
            }
        }

        if blocks.includeFooter {
            md += "\n\n---\n\n"
            md += "*📅 Generated by DayArc on \(Date().formatted(date: .numeric, time: .omitted))*\n"
        }

        Logger.shared.debug("🎨 Markdown: Final markdown length: \(md.count) chars", source: "MarkdownGen")

        // Log if AI section is present
        if md.contains("## 💡 AI 인사이트") {
            Logger.shared.info("✅ Markdown: AI insights section IS present in final markdown", source: "MarkdownGen")
        } else {
            Logger.shared.error("❌ Markdown: AI insights section NOT found in final markdown!", source: "MarkdownGen")
        }

        return md
    }

    // MARK: Weekly
    static func weekly(startDate: Date, endDate: Date, weeklyStats: DailyStats, dailyStats: [DailyStats], activities: [TimelineCard], analysis: AnalysisResult?, previousWeek: DailyStats?, chartPaths: [URL], language: ReportLanguage, blocks: ReportBlocks) -> String {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        let startStr = fmt.string(from: startDate)
        let endStr = fmt.string(from: endDate)

        // Calculate week number
        let calendar = Calendar.current
        let weekOfYear = calendar.component(.weekOfYear, from: startDate)
        let year = calendar.component(.year, from: startDate)
        let weekNumber = String(format: "%d-W%02d", year, weekOfYear)

        // Derived analyses
        let deepWorkAnalysis = StatsCalculator.calculateDeepWorkAnalysis(from: activities, thresholdMinutes: 25)
        let distractionAnalysis = StatsCalculator.calculateDistractionAnalysis(from: activities)

        // Find best productivity day
        let bestDay = dailyStats.max(by: { $0.productivityScore.totalScore < $1.productivityScore.totalScore })
        fmt.dateFormat = "yyyy-MM-dd"
        let bestDayStr = bestDay.map { fmt.string(from: $0.date) } ?? "-"
        let weekdayFmt = DateFormatter()
        weekdayFmt.locale = Locale(identifier: language == .korean ? "ko_KR" : "en_US_POSIX")
        weekdayFmt.dateFormat = "E"
        let bestDayWeekday = bestDay.map { "(\(weekdayFmt.string(from: $0.date)))" } ?? ""
        let bestDayScore = bestDay.map { String(format: "%.1f", $0.productivityScore.totalScore) } ?? "-"

        // Deep work ratio
        let deepWorkHours = deepWorkAnalysis.totalDeepWorkTime
        let deepWorkPercent = weeklyStats.totalActiveTime > 0 ? (deepWorkHours * 3600 / weeklyStats.totalActiveTime * 100) : 0

        var md = ""
        md += "---\n"
        md += "date: \(startStr)\n"
        md += "type: weekly-note\n"
        md += "week: \(weekNumber)\n"
        md += "productivity-score: \(Int(weeklyStats.productivityScore.totalScore))\n"
        md += "---\n\n"

        md += "# 🗓️ Weekly Review - \(weekNumber)\n\n"
        md += "**기간**: \(startStr) ~ \(endStr)\n\n"

        if blocks.includeTodo {
            md += "## 🎯 \(language == .korean ? "이번 주 핵심 목표" : "Weekly Goals")\n\n"
            md += "- [ ]\n"
            md += "- [ ]\n"
            md += "- [ ]\n\n"

            md += "## ✅ \(language == .korean ? "태스크 요약" : "Task Summary")\n\n"
            md += "- \(language == .korean ? "완료한 작업" : "Completed Tasks"):\n"
            md += "- \(language == .korean ? "이월된 작업" : "Carried Over Tasks"):\n\n"
        }

        if blocks.includeEmotion {
            md += "## 🧠 \(language == .korean ? "감정 & 집중 패턴 요약" : "Emotion & Focus Pattern Summary")\n\n"
            md += "- \(language == .korean ? "주요 감정" : "Dominant Emotion"):\n"
            md += "- \(language == .korean ? "집중 방해 요인" : "Distractions"):\n\n"
        }

        if blocks.includeRecap {
            md += "## 🥇 \(language == .korean ? "잘한 일" : "What Went Well")\n\n"
            md += "-\n\n"

            md += "## 🧱 \(language == .korean ? "부족했던 부분" : "Areas for Improvement")\n\n"
            md += "-\n\n"
        }

        if blocks.includeInsights {
            md += "## 💡 \(language == .korean ? "발견한 패턴" : "Discovered Patterns")\n\n"
            md += "> \(language == .korean ? "(예: 피로도가 높을수록 Slack 확인 횟수 증가 → 집중도 하락)" : "(e.g., Higher fatigue leads to more Slack checks → Lower focus)")\n\n"

            md += "## 🔁 \(language == .korean ? "다음 주 전략" : "Next Week Strategy")\n\n"
            md += "- \(language == .korean ? "루틴 개선" : "Routine Improvement"):\n"
            md += "- \(language == .korean ? "실험 대상" : "Experiment Target"):\n"
            md += "- \(language == .korean ? "협업 개선" : "Collaboration Improvement"):\n\n"
        }

        md += "\n---\n\n"

        if blocks.includeStats || blocks.includeCategoriesAndApps || blocks.includeCharts {
            md += "# 📊 Dayflow \(language == .korean ? "자동 분석" : "Auto Analysis")\n\n"
        }

        if blocks.includeStats {
            md += "## 📈 \(language == .korean ? "주간 통계" : "Weekly Statistics")\n\n"
            md += "- **\(language == .korean ? "총 업무 시간" : "Total Work Time")**: \(String(format: "%.1f", weeklyStats.totalActiveTime / 3600))h\n"
            md += "- **\(language == .korean ? "평균 생산성" : "Avg Productivity")**: \(Int(weeklyStats.productivityScore.totalScore))/100\n"
            md += "- **Deep Work**: \(String(format: "%.1f", deepWorkHours))h (\(Int(deepWorkPercent))%)\n"
            md += "- **\(language == .korean ? "최고의 하루" : "Best Day")**: \(bestDayStr) \(bestDayWeekday) - \(bestDayScore)\(language == .korean ? "점" : "pts")\n"
            md += "- **\(language == .korean ? "방해 앱 세션" : "Distracting App Sessions")**: \(distractionAnalysis.interruptionCount)\n\n"

            md += "## 📅 \(language == .korean ? "일별 생산성" : "Daily Productivity")\n\n"
            md += "| \(language == .korean ? "날짜" : "Date") | \(language == .korean ? "시간" : "Time") | \(language == .korean ? "생산성" : "Score") | Deep Work | \(language == .korean ? "주요 활동" : "Top Activity") |\n"
            md += "|------|------|-------|-----------|--------------|\n"

            fmt.dateFormat = "M/d (E)"
            fmt.locale = Locale(identifier: language == .korean ? "ko_KR" : "en_US_POSIX")

            for day in dailyStats.sorted(by: { $0.date < $1.date }) {
                let dateStr = fmt.string(from: day.date)
                let timeStr = String(format: "%.1fh", day.totalActiveTime / 3600)
                let scoreStr = String(format: "%.0f", day.productivityScore.totalScore)
                let topApp = day.topApps.first?.appName ?? "-"

                // Calculate deep work for this day (approximate if needed, but we have daily stats)
                // Note: DailyStats doesn't store deep work hours directly, so we might need to approximate or fetch
                // For now, let's use a placeholder or calculate if critical.
                // Actually, we passed dailyStats, but it doesn't have deepWorkHours.
                // We'll leave it as '-' for now or implement if critical.
                let dwStr = "-"

                md += "| \(dateStr) | \(timeStr) | \(scoreStr) | \(dwStr) | \(topApp) |\n"
            }
            md += "\n"
        }

        // Category breakdown
        if blocks.includeCategoriesAndApps {
            md += "\n## 📂 \(language == .korean ? "카테고리별 시간 분배" : "Time Distribution by Category")\n\n"
            md += "| \(language == .korean ? "카테고리" : "Category") | \(language == .korean ? "시간" : "Time") | \(language == .korean ? "비율" : "Ratio") |\n"
            md += "|---------|------|------|\n"

            for app in weeklyStats.topApps {
                md += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% |\n"
            }
            md += "\n"
        }

        // Top apps
        if blocks.includeCategoriesAndApps {
            md += "\n## 📱 \(language == .korean ? "가장 많이 사용한 앱/도구 (Top 10)" : "Most Used Apps/Tools (Top 10)")\n\n"
            md += "| \(language == .korean ? "순위" : "Rank") | \(language == .korean ? "앱/도구" : "App/Tool") | \(language == .korean ? "사용 시간" : "Usage Time") |\n"
            md += "|------|---------|----------|\n"

            for (idx, app) in weeklyStats.topApps.prefix(10).enumerated() {
                md += "| \(idx + 1) | \(app.appName) | \(app.formattedDuration) |\n"
            }
            md += "\n"
        }

        // AI suggestions
        if blocks.includeAISection {
            md += "\n## 💡 AI \(language == .korean ? "개선 제안" : "Improvement Suggestions")\n\n"

            if let analysis = analysis {
                md += analysis.summary + "\n\n"
                if !analysis.recommendations.isEmpty {
                    for rec in analysis.recommendations {
                        md += "\(rec)\n\n"
                    }
                }
            } else {
                md += "\(language == .korean ? "AI 개선 제안이 생성되지 않았습니다." : "AI improvement suggestions not generated.")\n"
            }
        }

        // Charts
        if blocks.includeCharts {
            md += "\n## 📈 \(language == .korean ? "주간 차트" : "Weekly Charts")\n\n"

            if chartPaths.count >= 1 {
                md += "### \(language == .korean ? "일별 생산성 추이" : "Daily Productivity Trend")\n"
                md += "![[charts/week_\(weekOfYear)_daily_trend.png]]\n\n"
            }
            if chartPaths.count >= 2 {
                md += "### \(language == .korean ? "카테고리별 시간 분배" : "Category Time Distribution")\n"
                md += "![[charts/week_\(weekOfYear)_category_breakdown.png]]\n\n"
            }
            if chartPaths.count >= 3 {
                md += "### \(language == .korean ? "요일별 생산성 패턴" : "Weekday Productivity Pattern")\n"
                md += "![[charts/week_\(weekOfYear)_weekday_pattern.png]]\n\n"
            }

            if chartPaths.isEmpty {
                md += "\(language == .korean ? "차트가 생성되지 않았습니다." : "Charts not generated.")\n"
            }
        }

        if blocks.includeFooter {
            md += "\n---\n\n*📅 Generated by DayArc on \(Date().formatted(date: .abbreviated, time: .omitted))*\n"
        }

        return md
    }

    // MARK: Monthly
    static func monthly(month: Date, monthlyStats: DailyStats, weeklyStats: [DailyStats], activities: [TimelineCard], analysis: AnalysisResult?, previousMonth: DailyStats?, chartPaths: [URL], language: ReportLanguage, blocks: ReportBlocks) -> String {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM"
        let monthStr = fmt.string(from: month)
        fmt.dateFormat = "yyyy년 M월"
        let display = fmt.string(from: month)

        // Calculate month and year for filename references
        let calendar = Calendar.current
        let year = calendar.component(.year, from: month)
        let monthNum = calendar.component(.month, from: month)

        // Find best productivity week
        let bestWeek = weeklyStats.enumerated().max(by: { $0.element.productivityScore.totalScore < $1.element.productivityScore.totalScore })
        let bestWeekStr = bestWeek.map { "주 \($0.offset + 1)" } ?? "-"
        let bestWeekScore = bestWeek.map { Int($0.element.productivityScore.totalScore) } ?? 0

        // Calculate deep work stats
        let deepWorkAnalysis = StatsCalculator.calculateDeepWorkAnalysis(from: activities, thresholdMinutes: 25)

        var md = ""
        md += "---\n"
        md += "date: \(monthStr)\n"
        md += "type: monthly-note\n"
        md += "month: \(monthStr)\n"
        md += "productivity-score: \(Int(monthlyStats.productivityScore.totalScore))\n"
        md += "---\n\n"

        md += "# 🧠 Monthly Review - \(display)\n\n"
        md += "**기간**: \(monthStr)\n\n"

        if blocks.includeTodo {
            md += "\n## 🎯 이번 달 핵심 주제/전략 키워드\n\n"
            md += "-\n\n"
        }

        if blocks.includeRecap {
            md += "\n## 📊 성과 요약\n\n"
            md += "### 달성한 것\n"
            md += "-\n\n"
            md += "### 진행 중\n"
            md += "-\n\n"
        }

        if blocks.includeInsights {
            md += "\n## 💡 인사이트 Top 3\n\n"
            md += "1.\n"
            md += "2.\n"
            md += "3.\n\n"
            md += "## ✅ 유효했던 실험/방법론\n\n"
            md += "-\n\n"
        }

        if blocks.includeRecap {
            md += "\n## 🚧 장애 요인\n\n"
            md += "-\n\n"
        }

        if blocks.includeTodo {
            md += "\n## 🎯 다음 달 전략\n\n"
            md += "-\n\n"
        }

        md += "\n---\n\n"

        if blocks.includeStats || blocks.includeCategoriesAndApps || blocks.includeCharts {
            md += "# 📊 Dayflow 자동 분석\n\n"
        }

        if blocks.includeStats {
            md += "## 📈 월간 통계\n\n"
            md += "- **총 업무 시간**: \(String(format: "%.1f", monthlyStats.totalActiveTime / 3600))시간\n"
            md += "- **평균 일일 업무**: \(String(format: "%.1f", (monthlyStats.totalActiveTime / 3600) / Double(max(1, calendar.range(of: .day, in: .month, for: month)?.count ?? 30))))시간\n"
            md += "- **총 Deep Work**: \(String(format: "%.1f", deepWorkAnalysis.totalDeepWorkTime))시간\n"
            md += "- **평균 생산성 점수**: \(Int(monthlyStats.productivityScore.totalScore))/100\n"
            md += "- **최고 생산성 주**: \(bestWeekStr) (\(bestWeekScore)점)\n\n"

            md += "## 📅 주간 생산성 추이\n\n"
            md += "| 주차 | 기간 | 업무시간 | 생산성 | Deep Work | 주요 활동 |\n"
            md += "|------|------|----------|--------|-----------|-----------|\n"

            // Weekly breakdown table
            fmt.dateFormat = "M/d"
            for (idx, ws) in weeklyStats.enumerated() {
                let wsDate = calendar.date(byAdding: .day, value: idx * 7, to: month) ?? month
                let weDate = calendar.date(byAdding: .day, value: 6, to: wsDate) ?? month
                let label = "주 \(idx + 1)"
                let period = "\(fmt.string(from: wsDate))-\(fmt.string(from: weDate))"
                let work = String(format: "%.1f", ws.totalActiveTime / 3600)
                let prod = String(format: "%.0f", ws.productivityScore.totalScore)
                let top = ws.topApps.first?.appName ?? "-"

                // Calculate weekly deep work
                // Note: We don't have per-week activities, so this is an approximation
                let weekDeepWork = String(format: "%.1fh", ws.deepWorkHours)

                md += "| \(label) | \(period) | \(work)h | \(prod) | \(weekDeepWork) | \(top) |\n"
            }
            md += "\n"
        }

        if blocks.includeAISection {
            md += "\n## 🔥 월간 생산성 패턴\n\n"

            if let analysis = analysis {
                md += "### 주요 발견사항\n"
                md += analysis.insights.map { "- " + $0 }.joined(separator: "\n") + "\n\n"

                md += "### 개선 방향\n"
                md += analysis.recommendations.map { "- " + $0 }.joined(separator: "\n") + "\n\n"
            }
        }

        if blocks.includeCategoriesAndApps {
            md += "\n## 📂 카테고리별 시간 분배 (월간)\n\n"
            md += "| 카테고리 | 시간 | 비율 | 전월 대비 |\n"
            md += "|----------|------|------|-----------|\n"

            for app in monthlyStats.topApps.prefix(10) {
                let prevComparison: String
                if let prev = previousMonth {
                    if let prevApp = prev.topApps.first(where: { $0.appName == app.appName }) {
                        let delta = app.duration - prevApp.duration
                        let deltaHours = delta / 3600.0
                        prevComparison = String(format: "%+.1fh", deltaHours)
                    } else {
                        prevComparison = "신규"
                    }
                } else {
                    prevComparison = "-"
                }
                md += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% | \(prevComparison) |\n"
            }
            md += "\n"
        }

        if blocks.includeCategoriesAndApps {
            md += "\n## 📱 월간 앱 사용 통계\n\n"
            md += "| 순위 | 앱/도구 | 시간 | 세션 수 |\n"
            md += "|------|---------|------|---------|\n"

            for (idx, app) in monthlyStats.topApps.prefix(15).enumerated() {
                md += "| \(idx + 1) | \(app.appName) | \(app.formattedDuration) | \(app.sessionCount) |\n"
            }
            md += "\n"
        }

        if blocks.includeAISection {
            md += "\n## 🤖 월간 회고 및 개선 제안\n\n"

            if let analysis = analysis {
                md += "### 종합 요약\n"
                md += analysis.summary + "\n\n"

                md += "### 구체적 개선 방향\n"
                md += analysis.recommendations.map { "- " + $0 }.joined(separator: "\n") + "\n\n"

                md += "*Generated by \(analysis.provider) (\(analysis.model))*\n\n"
            }
        }

        if blocks.includeHistory, let prev = previousMonth {
            fmt.dateFormat = "yyyy년 M월"
            let prevStr = fmt.string(from: prev.date)
            let totalTimeDelta = (monthlyStats.totalActiveTime - prev.totalActiveTime) / 3600.0
            let productivityDelta = monthlyStats.productivityScore.totalScore - prev.productivityScore.totalScore
            let deepWorkDelta = deepWorkAnalysis.totalDeepWorkTime -
                StatsCalculator.calculateDeepWorkAnalysis(from: activities, thresholdMinutes: 25).totalDeepWorkTime

            md += "\n## 📊 월간 성장 지표\n\n"
            md += "| 지표 | \(prevStr) | \(display) | 변화량 |\n"
            md += "|------|------------|----------|--------|\n"
            md += "| 총 업무 시간 | \(String(format: "%.1f", prev.totalActiveTime / 3600))h | \(String(format: "%.1f", monthlyStats.totalActiveTime / 3600))h | \(String(format: "%+.1f", totalTimeDelta))h |\n"
            md += "| 생산성 점수 | \(Int(prev.productivityScore.totalScore)) | \(Int(monthlyStats.productivityScore.totalScore)) | \(String(format: "%+.0f", productivityDelta)) |\n"
            md += "| Deep Work | - | \(String(format: "%.1f", deepWorkAnalysis.totalDeepWorkTime))h | - |\n"
            md += "| 주요 활동 | \(prev.topApps.first?.appName ?? "-") | \(monthlyStats.topApps.first?.appName ?? "-") | - |\n\n"
        }

        if blocks.includeCharts && !chartPaths.isEmpty {
            md += "\n## 📈 월간 시각화\n\n"

            // Add chart references based on what was generated
            for chartPath in chartPaths {
                let filename = chartPath.lastPathComponent

                // Add appropriate section heading based on chart type
                if filename.contains("heatmap") {
                    md += "\n### Monthly Productivity Heatmap\n"
                } else if filename.contains("app_breakdown") {
                    md += "\n### App Usage Breakdown\n"
                } else if filename.contains("weekly_trend") {
                    md += "\n### Weekly Productivity Trend\n"
                }

                md += "![[charts/\(filename)]]\n"
            }
        }

        if blocks.includeFooter {
            md += "\n---\n*Generated by DayArc on \(Date().formatted())*\n"
        }

        return md
    }
}
