//
//  MarkdownGenerator.swift
//  DayArc
//
//  Markdown template engine for generating Obsidian notes
//

import Foundation

class MarkdownGenerator {
    // MARK: - i18n
    struct LangStrings {
        let language: ReportLanguage

        enum Key {
            case startRoutine, todo, focusBlocks, emotion, insights, recap
            case dayflow, highlights, stats, history, aiAnalysis
            case topApps, timeline, charts, scorecard, recommendations, generatedBy
            case dailyBreakdown, weeklySummary, monthlySummary, categoryBreakdown, appBreakdown, patterns
        }

        func t(_ key: Key) -> String {
            switch (language, key) {
            case (.english, .startRoutine): return "Start Routine"
            case (.english, .todo): return "TODO"
            case (.english, .focusBlocks): return "Focus Blocks"
            case (.english, .emotion): return "Emotion & Flow"
            case (.english, .insights): return "Insights"
            case (.english, .recap): return "One-line Recap"
            case (.english, .dayflow): return "Dayflow Auto Analysis"
            case (.english, .highlights): return "Key Highlights"
            case (.english, .stats): return "Statistics"
            case (.english, .history): return "History / Delta"
            case (.english, .aiAnalysis): return "AI Analysis"
            case (.english, .topApps): return "Top Applications"
            case (.english, .timeline): return "Activity Timeline"
            case (.english, .charts): return "Charts"
            case (.english, .scorecard): return "Feature Utility Scorecard"
            case (.english, .recommendations): return "Recommendations"
            case (.english, .generatedBy): return "Generated by DayArc on"
            case (.english, .dailyBreakdown): return "Daily Breakdown"
            case (.english, .weeklySummary): return "Weekly Summary"
            case (.english, .monthlySummary): return "Monthly Summary"
            case (.english, .categoryBreakdown): return "Category Breakdown"
            case (.english, .appBreakdown): return "App Usage"
            case (.english, .patterns): return "Patterns"
            // Korean
            case (.korean, .startRoutine): return "시작 루틴"
            case (.korean, .todo): return "TODO"
            case (.korean, .focusBlocks): return "집중 블록"
            case (.korean, .emotion): return "감정 & 몰입"
            case (.korean, .insights): return "오늘의 통찰"
            case (.korean, .recap): return "한 줄 회고"
            case (.korean, .dayflow): return "Dayflow 자동 분석"
            case (.korean, .highlights): return "오늘의 핵심 하이라이트"
            case (.korean, .stats): return "통계"
            case (.korean, .history): return "히스토리 / 델타"
            case (.korean, .aiAnalysis): return "AI 분석"
            case (.korean, .topApps): return "상위 앱"
            case (.korean, .timeline): return "활동 타임라인"
            case (.korean, .charts): return "차트"
            case (.korean, .scorecard): return "기능 유틸리티 점수표"
            case (.korean, .recommendations): return "추천/액션아이템"
            case (.korean, .generatedBy): return "Generated by DayArc on"
            case (.korean, .dailyBreakdown): return "일별 생산성"
            case (.korean, .weeklySummary): return "주간 요약"
            case (.korean, .monthlySummary): return "월간 요약"
            case (.korean, .categoryBreakdown): return "카테고리별 분배"
            case (.korean, .appBreakdown): return "앱 사용"
            case (.korean, .patterns): return "패턴"
            }
        }
    }

    struct HistoricalContext {
        let last7AvgScore: Double
        let last7AvgHours: Double
        let last30AvgScore: Double
        let last30AvgHours: Double

        func deviationNotes(currentScore: Double, language: ReportLanguage) -> [String] {
            var notes: [String] = []
            let d7 = currentScore - last7AvgScore
            let d30 = currentScore - last30AvgScore

            if d7 < -10 {
                notes.append(language == .korean ? "최근 7일 평균 대비 \(String(format: "%.1f", abs(d7)))p 하락" : "Down \(String(format: "%.1f", abs(d7))) vs 7-day avg")
            } else if d7 > 10 {
                notes.append(language == .korean ? "최근 7일 평균 대비 \(String(format: "%.1f", d7))p 상승" : "Up \(String(format: "%.1f", d7)) vs 7-day avg")
            }

            if d30 < -10 {
                notes.append(language == .korean ? "최근 30일 평균 대비 \(String(format: "%.1f", abs(d30)))p 하락" : "Down \(String(format: "%.1f", abs(d30))) vs 30-day avg")
            } else if d30 > 10 {
                notes.append(language == .korean ? "최근 30일 평균 대비 \(String(format: "%.1f", d30))p 상승" : "Up \(String(format: "%.1f", d30)) vs 30-day avg")
            }

            return notes
        }
    }

    // MARK: - Daily Note Generation

    /// Generate daily note markdown
    static func generateDailyNote(
        date: Date,
        stats: DailyStats,
        analysis: AnalysisResult?,
        activities: [TimelineCard],
        history: HistoricalContext?,
        chartPaths: [URL] = []
    ) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let dateString = formatter.string(from: date)

        formatter.dateFormat = "EEEE, MMMM d, yyyy"
        let fullDateString = formatter.string(from: date)

        var markdown = """
        ---
        date: \(dateString)
        type: daily-note
        productivity-score: \(Int(stats.productivityScore.totalScore))
        total-time: \(Int(stats.totalActiveTime / 3600))h
        ---

        # 📅 \(fullDateString)

        ## 📊 Productivity Summary

        **Overall Score:** \(Int(stats.productivityScore.totalScore))/100 (\(stats.productivityScore.category))

        | Metric | Score | Rating |
        |--------|-------|--------|
        | 🎯 Deep Work | \(Int(stats.productivityScore.deepWorkScore))/100 | \(ratingBar(stats.productivityScore.deepWorkScore)) |
        | 🎨 Diversity | \(Int(stats.productivityScore.diversityScore))/100 | \(ratingBar(stats.productivityScore.diversityScore)) |
        | 🚫 Distraction | \(Int(stats.productivityScore.distractionScore))/100 | \(ratingBar(stats.productivityScore.distractionScore)) |
        | ⚡ Consistency | \(Int(stats.productivityScore.consistencyScore))/100 | \(ratingBar(stats.productivityScore.consistencyScore)) |

        ### 📈 Statistics

        - **Total Active Time:** \(stats.formattedActiveTime)
        - **Activities Tracked:** \(stats.totalActivities)
        - **Apps Used:** \(stats.uniqueApps)

        """

        if let history = history {
            markdown += """

            ## 📈 Historical Context

            - **7-day Avg Score:** \(Int(history.last7AvgScore))/100, **Avg Hours:** \(String(format: "%.1f", history.last7AvgHours))
            - **30-day Avg Score:** \(Int(history.last30AvgScore))/100, **Avg Hours:** \(String(format: "%.1f", history.last30AvgHours))
            - **Δ vs 7-day:** \(deltaString(current: stats.productivityScore.totalScore, baseline: history.last7AvgScore))
            - **Δ vs 30-day:** \(deltaString(current: stats.productivityScore.totalScore, baseline: history.last30AvgScore))

            """

            let deviations = history.deviationNotes(currentScore: stats.productivityScore.totalScore, language: .korean)
            if !deviations.isEmpty {
                markdown += deviations.map { "- \( $0)" }.joined(separator: "\n") + "\n"
            }
        }

        // Add AI Analysis if available
        if let analysis = analysis {
            markdown += """

            ## 🤖 AI Analysis

            ### Summary
            \(analysis.summary)

            ### Key Insights
            \(analysis.insights.map { "- " + $0 }.joined(separator: "\n"))

            ### Recommendations
            \(analysis.recommendations.map { "- " + $0 }.joined(separator: "\n"))

            *Generated by \(analysis.provider) (\(analysis.model))*

            """
        } else {
            markdown += """

            ## 🤖 AI Analysis

            - LLM 응답이 없습니다. 키 설정과 네트워크 상태를 확인하세요.

            """
        }

        // Add Top Apps
        markdown += """

        ## 📱 Top Applications

        | App | Time | Percentage |
        |-----|------|------------|
        """

        for app in stats.topApps.prefix(10) {
            markdown += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% |\n"
        }

        // Add Activity Timeline
        markdown += """

        ## 🕐 Activity Timeline

        ```timeline
        """

        let calendar = Calendar.current
        for activity in activities.prefix(50) { // Limit to first 50
            let hour = calendar.component(.hour, from: activity.startAt)
            let minute = calendar.component(.minute, from: activity.startAt)
            let durationMin = Int(activity.duration / 60)

            markdown += "\(String(format: "%02d:%02d", hour, minute)) - \(activity.appName) (\(durationMin)m)\n"
        }

        markdown += """
        ```

        ---
        *Generated by DayArc on \(Date().formatted())*

        ## 🧪 Feature Utility Scorecard

        | 항목 | 점수(1-5) | 설명 |
        |------|-----------|------|
        | AI 요약/인사이트 | \(analysis != nil ? "5" : "3") | \(analysis != nil ? "LLM 요약 포함" : "추가 요약 필요") |
        | 추천/액션아이템 | \(analysis != nil ? "4" : "2") | \(analysis != nil ? "AI 추천 제공" : "기본 통계 중심") |
        | 앱/활동 통계 | 4 | 상위 앱·타임라인 제공 |
        | 시각화(그래프) | 2 | 표/타임라인 제공(그래프 추가 필요) |
        | 흐름/트렌드 비교 | \(history != nil ? "4" : "2") | \(history != nil ? "7/30일 비교 제공" : "단일 일 기준") |

        ### 개선 제안
        - 그래프(카테고리/시간대/Deep vs Shallow) 추가
        - 목표/컨텍스트 주입한 AI 액션 아이템 강화
        - 최근 7/30일 대비 세부 증감 표 추가

        """

        // Insert chart references if available
        if !chartPaths.isEmpty {
            markdown += """

            ## 📊 Charts
            \(chartPaths.map { "![Chart](\($0.path))" }.joined(separator: "\n"))

            """
        } else {
            markdown += """

        ## 📊 Charts
        그래프가 생성되지 않았습니다 (macOS 14+ 및 Swift Charts 필요).

        """
        }

        return markdown
    }

    // MARK: - Weekly Note Generation

    /// Generate weekly note markdown
    static func generateWeeklyNote(
        startDate: Date,
        endDate: Date,
        weeklyStats: DailyStats,
        dailyStats: [DailyStats],
        analysis: AnalysisResult?,
        previousWeek: DailyStats?,
        chartPaths: [URL] = []
    ) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let startString = formatter.string(from: startDate)
        let endString = formatter.string(from: endDate)

        formatter.dateFormat = "MMMM d"
        let startDisplay = formatter.string(from: startDate)
        let endDisplay = formatter.string(from: endDate)

        var markdown = """
        ---
        date: \(startString)
        type: weekly-note
        week-of: \(startString)
        productivity-score: \(Int(weeklyStats.productivityScore.totalScore))
        ---

        # 📅 Week of \(startDisplay) - \(endDisplay)

        ## 📊 Weekly Summary

        **Average Productivity Score:** \(Int(weeklyStats.productivityScore.totalScore))/100

        ### Weekly Statistics
        - **Total Active Time:** \(weeklyStats.formattedActiveTime)
        - **Total Activities:** \(weeklyStats.totalActivities)
        - **Unique Apps:** \(weeklyStats.uniqueApps)

        ## 📈 Daily Breakdown

        | Date | Score | Active Time | Top App |
        |------|-------|-------------|---------|
        """

        for stats in dailyStats.sorted(by: { $0.date < $1.date }) {
            formatter.dateFormat = "MMM d (EEE)"
            let dateStr = formatter.string(from: stats.date)
            let topApp = stats.topApps.first?.appName ?? "N/A"

            markdown += "| \(dateStr) | \(Int(stats.productivityScore.totalScore)) | \(stats.formattedActiveTime) | \(topApp) |\n"
        }

        markdown += """

        ## 🏆 Top Applications (Week)

        | App | Total Time | Percentage |
        |-----|-----------|------------|
        """

        for app in weeklyStats.topApps.prefix(15) {
            markdown += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% |\n"
        }

        markdown += """

        ## 💡 Weekly Insights

        ### Productivity Trends
        - **Best Day:** \(bestDay(from: dailyStats))
        - **Most Consistent:** \(mostConsistent(from: dailyStats))
        - **Average Score:** \(Int(averageScore(from: dailyStats)))/100

        """

        if let previousWeek = previousWeek {
            markdown += """

        ### 📊 Week-over-Week
        - **Score:** \(Int(weeklyStats.productivityScore.totalScore)) (\(deltaString(current: weeklyStats.productivityScore.totalScore, baseline: previousWeek.productivityScore.totalScore)))
        - **Active Time:** \(weeklyStats.formattedActiveTime) (prev \(previousWeek.formattedActiveTime))
        - **Top App:** \(weeklyStats.topApps.first?.appName ?? "N/A") (prev \(previousWeek.topApps.first?.appName ?? "N/A"))

        """
        }

        if let analysis = analysis {
            markdown += """

        ## 🤖 AI Weekly Insights

        ### Summary
        \(analysis.summary)

        ### Key Insights
        \(analysis.insights.map { "- " + $0 }.joined(separator: "\n"))

        ### Recommendations
        \(analysis.recommendations.map { "- " + $0 }.joined(separator: "\n"))

        *Generated by \(analysis.provider) (\(analysis.model))*

        """
        } else {
        markdown += """

        ## 🤖 AI Weekly Insights

        - LLM 응답이 없습니다. 키 설정과 네트워크 상태를 확인하세요.

        """
        }

        markdown += """

        ## 🧪 Feature Utility Scorecard

        | 항목 | 점수(1-5) | 설명 |
        |------|-----------|------|
        | AI 요약/인사이트 | \(analysis != nil ? "5" : "3") | \(analysis != nil ? "주간 LLM 요약 포함" : "추가 요약 필요") |
        | 추천/액션아이템 | \(analysis != nil ? "4" : "2") | \(analysis != nil ? "AI 추천 제공" : "기본 통계 중심") |
        | 앱/활동 통계 | 4 | 일별/주간 집계 제공 |
        | 시각화(그래프) | 2 | 표/트렌드 제공(그래프 추가 필요) |
        | 흐름/트렌드 비교 | \(previousWeek != nil ? "4" : "3") | \(previousWeek != nil ? "전주 대비 비교 제공" : "단일 주 기준") |

        ### 개선 제안
        - 그래프(주간 추이/카테고리 분포) 추가
        - 전주 대비 증감 세부 표/그래프화
        - AI 액션 아이템을 OKR/목표와 연결

        ---
        *Generated by DayArc on \(Date().formatted())*

        """

        if !chartPaths.isEmpty {
            markdown += """

        ## 📊 Charts
        \(chartPaths.map { "![Chart](\($0.path))" }.joined(separator: "\n"))

        """
        }

        return markdown
    }

    // MARK: - Monthly Note Generation

    /// Generate monthly note markdown
    static func generateMonthlyNote(
        month: Date,
        monthlyStats: DailyStats,
        weeklyStats: [DailyStats],
        analysis: AnalysisResult?,
        previousMonth: DailyStats?,
        chartPaths: [URL] = []
    ) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM"
        let monthString = formatter.string(from: month)

        formatter.dateFormat = "MMMM yyyy"
        let monthDisplay = formatter.string(from: month)

        var markdown = """
        ---
        date: \(monthString)
        type: monthly-note
        month: \(monthString)
        productivity-score: \(Int(monthlyStats.productivityScore.totalScore))
        ---

        # 📅 \(monthDisplay)

        ## 📊 Monthly Overview

        **Overall Productivity Score:** \(Int(monthlyStats.productivityScore.totalScore))/100

        ### Monthly Statistics
        - **Total Active Time:** \(monthlyStats.formattedActiveTime)
        - **Total Activities:** \(monthlyStats.totalActivities)
        - **Unique Apps Used:** \(monthlyStats.uniqueApps)

        ## 📈 Weekly Performance

        | Week | Score | Active Time |
        |------|-------|-------------|
        """

        for (index, stats) in weeklyStats.enumerated() {
            markdown += "| Week \(index + 1) | \(Int(stats.productivityScore.totalScore)) | \(stats.formattedActiveTime) |\n"
        }

        markdown += """

        ## 🏆 Top Applications (Month)

        | App | Total Time | Percentage |
        |-----|-----------|------------|
        """

        for app in monthlyStats.topApps.prefix(20) {
            markdown += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% |\n"
        }

        markdown += """

        ## 💡 Monthly Insights

        - **Average Daily Score:** \(Int(averageScore(from: weeklyStats)))/100
        - **Most Productive Week:** Week \(mostProductiveWeek(from: weeklyStats))
        - **Total Working Days:** \(weeklyStats.count * 7) days tracked

        """

        if let prev = previousMonth {
            markdown += "\n### 📊 Month-over-Month\n"
            markdown += "- **Score:** \(Int(monthlyStats.productivityScore.totalScore)) (\(deltaString(current: monthlyStats.productivityScore.totalScore, baseline: prev.productivityScore.totalScore)))\n"
            markdown += "- **Active Time:** \(monthlyStats.formattedActiveTime) (prev \(prev.formattedActiveTime))\n"
            markdown += "- **Unique Apps:** \(monthlyStats.uniqueApps) (prev \(prev.uniqueApps))\n"
        }

        if let analysis = analysis {
            markdown += """

        ## 🤖 AI Monthly Insights

        ### Summary
        \(analysis.summary)

        ### Key Insights
        \(analysis.insights.map { "- " + $0 }.joined(separator: "\n"))

        ### Recommendations
        \(analysis.recommendations.map { "- " + $0 }.joined(separator: "\n"))

        *Generated by \(analysis.provider) (\(analysis.model))*

        """
        } else {
        markdown += """

        ## 🤖 AI Monthly Insights

        - LLM 응답이 없습니다. 키 설정과 네트워크 상태를 확인하세요.

        """
        }

        markdown += """

        ## 🧪 Feature Utility Scorecard

        | 항목 | 점수(1-5) | 설명 |
        |------|-----------|------|
        | AI 요약/인사이트 | \(analysis != nil ? "5" : "3") | \(analysis != nil ? "월간 LLM 인사이트 포함" : "추가 요약 필요") |
        | 추천/액션아이템 | \(analysis != nil ? "4" : "2") | \(analysis != nil ? "AI 추천 제공" : "기본 통계 중심") |
        | 앱/활동 통계 | 4 | 주차별/월간 집계 제공 |
        | 시각화(그래프) | 2 | 표 기반(그래프 추가 필요) |
        | 흐름/트렌드 비교 | \(previousMonth != nil ? "4" : "3") | \(previousMonth != nil ? "전월 대비 비교 제공" : "단일 월 기준") |

        ### 개선 제안
        - 그래프(카테고리/시간대/변동 추이) 추가
        - 카테고리/앱 Top-N 변화 그래프화
        - 목표/OKR 기반 월간 액션 아이템 강화

        ---
        *Generated by DayArc on \(Date().formatted())*

        """

        if !chartPaths.isEmpty {
            markdown += """

        ## 📊 Charts
        \(chartPaths.map { "![Chart](\($0.path))" }.joined(separator: "\n"))

        """
        } else {
            markdown += """

        ## 📊 Charts
        그래프가 생성되지 않았습니다 (macOS 14+ 및 Swift Charts 필요).

        """
        }

        return markdown
    }

    // MARK: - Helper Functions

    /// Generate rating bar visualization
    static func ratingBar(_ score: Double) -> String {
        let filled = Int(score / 10)
        let empty = 10 - filled
        return String(repeating: "█", count: filled) + String(repeating: "░", count: empty)
    }

    /// Find best day from daily stats
    private static func bestDay(from stats: [DailyStats]) -> String {
        guard let best = stats.max(by: { $0.productivityScore.totalScore < $1.productivityScore.totalScore }) else {
            return "N/A"
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        return "\(formatter.string(from: best.date)) (\(Int(best.productivityScore.totalScore)))"
    }

    /// Find most consistent day
    private static func mostConsistent(from stats: [DailyStats]) -> String {
        guard let best = stats.max(by: { $0.productivityScore.consistencyScore < $1.productivityScore.consistencyScore }) else {
            return "N/A"
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        return formatter.string(from: best.date)
    }

    /// Calculate average score
    private static func averageScore(from stats: [DailyStats]) -> Double {
        guard !stats.isEmpty else { return 0 }
        let total = stats.reduce(0.0) { $0 + $1.productivityScore.totalScore }
        return total / Double(stats.count)
    }

    /// Calculate average hours
    private static func averageHours(from stats: [DailyStats]) -> Double {
        guard !stats.isEmpty else { return 0 }
        let totalSeconds = stats.reduce(0.0) { $0 + $1.totalActiveTime }
        return (totalSeconds / Double(stats.count)) / 3600.0
    }

    /// Find most productive week index
    private static func mostProductiveWeek(from stats: [DailyStats]) -> Int {
        guard !stats.isEmpty,
              let maxIndex = stats.enumerated().max(by: { $0.element.productivityScore.totalScore < $1.element.productivityScore.totalScore })?.offset else {
            return 1
        }
        return maxIndex + 1
    }

    /// Delta string between current and baseline
    static func deltaString(current: Double, baseline: Double) -> String {
        let delta = current - baseline
        let arrow = delta > 0 ? "▲" : (delta < 0 ? "▼" : "・")
        return "\(arrow) \(String(format: "%.1f", delta))"
    }
}
