//
//  MarkdownGeneratorV2.swift
//  DayArc
//
//  New modular, i18n-enabled markdown generator.
//

import Foundation

struct MarkdownGeneratorV2 {
    // MARK: Strings
    struct LangStrings {
        let language: ReportLanguage
        enum Key {
            case startRoutine, todo, focusBlocks, emotion, insights, recap
            case dayflow, highlights, stats, history, aiAnalysis
            case topApps, timeline, charts, scorecard, recommendations, generatedBy
            case dailyBreakdown, weeklySummary, monthlySummary, categoryBreakdown, appBreakdown, patterns
        }
        func t(_ key: Key) -> String {
            switch (language, key) {
            case (.english, .startRoutine): return "Start Routine"
            case (.english, .todo): return "TODO"
            case (.english, .focusBlocks): return "Focus Blocks"
            case (.english, .emotion): return "Emotion & Flow"
            case (.english, .insights): return "Insights"
            case (.english, .recap): return "One-line Recap"
            case (.english, .dayflow): return "Dayflow Auto Analysis"
            case (.english, .highlights): return "Key Highlights"
            case (.english, .stats): return "Statistics"
            case (.english, .history): return "History / Delta"
            case (.english, .aiAnalysis): return "AI Analysis"
            case (.english, .topApps): return "Top Applications"
            case (.english, .timeline): return "Activity Timeline"
            case (.english, .charts): return "Charts"
            case (.english, .scorecard): return "Feature Utility Scorecard"
            case (.english, .recommendations): return "Recommendations"
            case (.english, .generatedBy): return "Generated by DayArc on"
            case (.english, .dailyBreakdown): return "Daily Breakdown"
            case (.english, .weeklySummary): return "Weekly Summary"
            case (.english, .monthlySummary): return "Monthly Summary"
            case (.english, .categoryBreakdown): return "Category Breakdown"
            case (.english, .appBreakdown): return "App Usage"
            case (.english, .patterns): return "Patterns"
            case (.korean, .startRoutine): return "시작 루틴"
            case (.korean, .todo): return "TODO"
            case (.korean, .focusBlocks): return "집중 블록"
            case (.korean, .emotion): return "감정 & 몰입"
            case (.korean, .insights): return "오늘의 통찰"
            case (.korean, .recap): return "한 줄 회고"
            case (.korean, .dayflow): return "Dayflow 자동 분석"
            case (.korean, .highlights): return "오늘의 핵심 하이라이트"
            case (.korean, .stats): return "통계"
            case (.korean, .history): return "히스토리 / 델타"
            case (.korean, .aiAnalysis): return "AI 분석"
            case (.korean, .topApps): return "상위 앱"
            case (.korean, .timeline): return "활동 타임라인"
            case (.korean, .charts): return "차트"
            case (.korean, .scorecard): return "기능 유틸리티 점수표"
            case (.korean, .recommendations): return "추천/액션아이템"
            case (.korean, .generatedBy): return "Generated by DayArc on"
            case (.korean, .dailyBreakdown): return "일별 생산성"
            case (.korean, .weeklySummary): return "주간 요약"
            case (.korean, .monthlySummary): return "월간 요약"
            case (.korean, .categoryBreakdown): return "카테고리별 분배"
            case (.korean, .appBreakdown): return "앱 사용"
            case (.korean, .patterns): return "패턴"
            }
        }
    }

    // MARK: Public generators
    static func daily(
        date: Date,
        stats: DailyStats,
        analysis: AnalysisResult?,
        activities: [TimelineCard],
        history: MarkdownGenerator.HistoricalContext?,
        chartPaths: [URL],
        language: ReportLanguage,
        blocks: ReportBlocks
    ) -> String {
        let s = LangStrings(language: language)
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        let dateString = formatter.string(from: date)
        formatter.dateFormat = language == .korean ? "yyyy년 M월 d일 EEEE" : "EEEE, MMMM d, yyyy"
        let fullDateString = formatter.string(from: date)

        var md = """
        ---
        date: \(dateString)
        type: daily-note
        productivity-score: \(Int(stats.productivityScore.totalScore))
        total-time: \(Int(stats.totalActiveTime / 3600))h
        ---

        # 📅 \(fullDateString)

        ## 📊 \(s.t(.stats))

        **Overall Score:** \(Int(stats.productivityScore.totalScore))/100 (\(stats.productivityScore.category))

        | Metric | Score | Rating |
        |--------|-------|--------|
        | 🎯 Deep Work | \(Int(stats.productivityScore.deepWorkScore))/100 | \(MarkdownGenerator.ratingBar(stats.productivityScore.deepWorkScore)) |
        | 🎨 Diversity | \(Int(stats.productivityScore.diversityScore))/100 | \(MarkdownGenerator.ratingBar(stats.productivityScore.diversityScore)) |
        | 🚫 Distraction | \(Int(stats.productivityScore.distractionScore))/100 | \(MarkdownGenerator.ratingBar(stats.productivityScore.distractionScore)) |
        | ⚡ Consistency | \(Int(stats.productivityScore.consistencyScore))/100 | \(MarkdownGenerator.ratingBar(stats.productivityScore.consistencyScore)) |
        """

        if blocks.includeStartRoutine {
            md += """

            ## ☀️ \(s.t(.startRoutine))
            - [ ] \(language == .korean ? "기상 시간" : "Wake-up time"):
            - [ ] \(language == .korean ? "수면 시간" : "Sleep time"):
            - [ ] \(language == .korean ? "컨디션 (1~10)" : "Condition (1~10)"):
            """
        }
        if blocks.includeTodo {
            md += """

            ## 🎯 \(s.t(.todo))
            - [ ]
            - [ ]
            - [ ]
            """
        }
        if blocks.includeFocusBlocks {
            md += """

            ## ⌛ \(s.t(.focusBlocks))
            | \(language == .korean ? "시간" : "Time") | \(language == .korean ? "활동" : "Activity") | \(language == .korean ? "집중도" : "Focus") | \(language == .korean ? "방해요소" : "Distraction") | \(language == .korean ? "개선점" : "Improvement") |
            |---|---|---|---|---|
            |||||
            """
        }
        if blocks.includeEmotion {
            md += """

            ## 🧠 \(s.t(.emotion))
            - \(language == .korean ? "감정 점수" : "Mood score"):
            - \(language == .korean ? "잘한 것 & 좋았던 것" : "What went well"):
            - \(language == .korean ? "못한 것 & 안좋았던 것" : "What to improve"):
            """
        }
        if blocks.includeInsights {
            md += """

            ## 💡 \(s.t(.insights))
            >
            """
        }
        if blocks.includeRecap {
            md += """

            ## 🔁 \(s.t(.recap))
            >
            """
        }
        if let history = history, blocks.includeHistory {
            md += """

            ## 📈 \(s.t(.history))
            - 7d Avg: \(Int(history.last7AvgScore))/100, Hrs: \(String(format: "%.1f", history.last7AvgHours))
            - 30d Avg: \(Int(history.last30AvgScore))/100, Hrs: \(String(format: "%.1f", history.last30AvgHours))
            - Δ vs 7d: \(MarkdownGenerator.deltaString(current: stats.productivityScore.totalScore, baseline: history.last7AvgScore))
            - Δ vs 30d: \(MarkdownGenerator.deltaString(current: stats.productivityScore.totalScore, baseline: history.last30AvgScore))
            """
            let deviations = history.deviationNotes(currentScore: stats.productivityScore.totalScore, language: language)
            if !deviations.isEmpty {
                md += "\n" + deviations.map { "- \($0)" }.joined(separator: "\n")
            }
        }

        if blocks.includeAISection, let analysis = analysis {
            md += """

            ## 🤖 \(s.t(.aiAnalysis))
            ### \(language == .korean ? "요약" : "Summary")
            \(analysis.summary)

            ### \(language == .korean ? "핵심 인사이트" : "Key Insights")
            \(analysis.insights.map { "- " + $0 }.joined(separator: "\n"))

            ### \(s.t(.recommendations))
            \(analysis.recommendations.map { "- " + $0 }.joined(separator: "\n"))

            *Generated by \(analysis.provider) (\(analysis.model))*
            """
        } else if blocks.includeAISection {
            md += """

            ## 🤖 \(s.t(.aiAnalysis))
            - \(language == .korean ? "LLM 응답이 없습니다. 키 설정과 네트워크 상태를 확인하세요." : "No LLM response. Check API key and network.")
            """
        }

        if blocks.includeCategoriesAndApps {
            md += """

            ## 📱 \(s.t(.topApps))
            | \(language == .korean ? "앱" : "App") | \(language == .korean ? "시간" : "Time") | % |
            |-----|------|------------|
            """
            for app in stats.topApps.prefix(10) {
                md += "| \(app.appName) | \(app.formattedDuration) | \(String(format: "%.1f", app.percentage))% |\n"
            }
        }

        if blocks.includeTimeline {
            md += "\n## 🕐 \(s.t(.timeline))\n\n```timeline\n"
            let cal = Calendar.current
            for activity in activities.prefix(50) {
                let h = cal.component(.hour, from: activity.startAt)
                let m = cal.component(.minute, from: activity.startAt)
                let d = Int(activity.duration / 60)
                md += String(format: "%02d:%02d - %@ (%dm)\n", h, m, activity.appName, d)
            }
            md += "```\n"
        }

        if blocks.includeScorecard {
            md += """

            ## 🧪 \(s.t(.scorecard))
            | \(language == .korean ? "항목" : "Item") | \(language == .korean ? "점수(1-5)" : "Score(1-5)") | \(language == .korean ? "설명" : "Notes") |
            |------|-----------|------|
            | AI | \(analysis != nil ? "5" : "3") | \(analysis != nil ? (language == .korean ? "LLM 요약 포함" : "LLM summary included") : (language == .korean ? "추가 요약 필요" : "Needs summary")) |
            | \(s.t(.recommendations)) | \(analysis != nil ? "4" : "2") | \(analysis != nil ? (language == .korean ? "AI 추천 제공" : "AI recommendations") : (language == .korean ? "기본 통계 중심" : "Stats only")) |
            | \(s.t(.appBreakdown)) | 4 | \(language == .korean ? "상위 앱·타임라인 제공" : "Top apps & timeline") |
            | \(s.t(.charts)) | \(chartPaths.isEmpty ? "2" : "4") | \(chartPaths.isEmpty ? (language == .korean ? "그래프 없음" : "Charts missing") : (language == .korean ? "그래프 포함" : "Charts included")) |
            | \(s.t(.history)) | \(history != nil ? "4" : "2") | \(history != nil ? (language == .korean ? "7/30일 비교 제공" : "7/30d comparison") : (language == .korean ? "단일 일 기준" : "Single day only")) |
            """
        }

        if blocks.includeCharts {
            if chartPaths.isEmpty {
                md += "\n## 📊 \(s.t(.charts))\n\(language == .korean ? "그래프가 생성되지 않았습니다 (macOS 14+ 필요)." : "Charts not generated (requires macOS 14+).")\n"
            } else {
                md += "\n## 📊 \(s.t(.charts))\n\(chartPaths.map { \"![Chart](\\($0.path))\" }.joined(separator: \"\\n\"))\n"
            }
        }

        if blocks.includeFooter {
            md += "\n---\n*\(s.t(.generatedBy)) \(Date().formatted())*\n"
        }

        return md
    }

    static func weekly(
        startDate: Date,
        endDate: Date,
        weeklyStats: DailyStats,
        dailyStats: [DailyStats],
        analysis: AnalysisResult?,
        previousWeek: DailyStats?,
        chartPaths: [URL],
        language: ReportLanguage,
        blocks: ReportBlocks
    ) -> String {
        let s = LangStrings(language: language)
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        let startStr = fmt.string(from: startDate)

        fmt.dateFormat = language == .korean ? "M월 d일" : "MMM d"
        let startDisp = fmt.string(from: startDate)
        let endDisp = fmt.string(from: endDate)

        var md = \"\"\"\n        ---\n        date: \(startStr)\n        type: weekly-note\n        week-of: \(startStr)\n        productivity-score: \(Int(weeklyStats.productivityScore.totalScore))\n        ---\n\n        # 📅 Week of \(startDisp) - \(endDisp)\n\n        ## 📊 \(s.t(.weeklySummary))\n        - \(language == .korean ? \"총 업무 시간\" : \"Total Work Hours\"): \(String(format: \"%.1f\", weeklyStats.totalActiveTime / 3600))\n        - \(language == .korean ? \"일 평균 업무\" : \"Avg Daily Work\"): \(String(format: \"%.1f\", (weeklyStats.totalActiveTime / 3600) / 7))\n        - \(language == .korean ? \"평균 생산성\" : \"Average Productivity\"): \(Int(weeklyStats.productivityScore.totalScore))/100\n        \"\"\"\n\n        if blocks.includeStats {\n            md += \"\"\"\n\n            ## 📅 \(s.t(.dailyBreakdown))\n            | \(language == .korean ? \"날짜\" : \"Date\") | \(language == .korean ? \"요일\" : \"Day\") | \(language == .korean ? \"업무시간\" : \"Work Hours\") | \(language == .korean ? \"집중시간\" : \"Focus Hours\") | \(language == .korean ? \"생산성\" : \"Productivity\") | \(language == .korean ? \"주요 활동\" : \"Top Activity\") |\n            |------|-----|------------|-------------|--------------|--------------|\n            \"\"\"\n            fmt.dateFormat = \"yyyy-MM-dd\"\n            let weekday = DateFormatter()\n            weekday.locale = Locale(identifier: language == .korean ? \"ko_KR\" : \"en_US_POSIX\")\n            weekday.dateFormat = \"E\"\n            for ds in dailyStats {\n                let d = fmt.string(from: ds.date)\n                let w = weekday.string(from: ds.date)\n                let work = String(format: \"%.1f\", ds.totalActiveTime / 3600)\n                let focus = String(format: \"%.1f\", ds.productivityScore.deepWorkScore / 100 * (ds.totalActiveTime / 3600))\n                let prod = String(format: \"%.1f\", ds.productivityScore.totalScore)\n                let top = ds.topApps.first?.appName ?? \"-\"\n                md += \"| \\(d) | \\(w) | \\(work)h | \\(focus)h | \\(prod) | \\(top) |\\n\"\n            }\n        }\n\n        if let prev = previousWeek, blocks.includeHistory {\n            md += \"\\n## 📈 \(s.t(.history))\\n- \(language == .korean ? \"이전 주 점수\" : \"Previous week score\"): \(Int(prev.productivityScore.totalScore))/100\\n- Δ: \(MarkdownGenerator.deltaString(current: weeklyStats.productivityScore.totalScore, baseline: prev.productivityScore.totalScore))\\n\"\n        }\n\n        if blocks.includeAISection, let analysis = analysis {\n            md += \"\"\"\n\n            ## 🤖 \(s.t(.aiAnalysis))\n            ### \(language == .korean ? \"요약\" : \"Summary\")\n            \(analysis.summary)\n\n            ### \(s.t(.patterns))\n            \(analysis.insights.map { \"- \" + $0 }.joined(separator: \"\\n\"))\n\n            ### \(s.t(.recommendations))\n            \(analysis.recommendations.map { \"- \" + $0 }.joined(separator: \"\\n\"))\n\n            *Generated by \(analysis.provider) (\(analysis.model))*\n            \"\"\"\n        } else if blocks.includeAISection {\n            md += \"\\n## 🤖 \(s.t(.aiAnalysis))\\n- \(language == .korean ? \"이번 주 AI 인사이트가 없습니다.\" : \"No AI insights for this week.\")\\n\"\n        }\n\n        if blocks.includeCategoriesAndApps {\n            md += \"\\n## 📂 \(s.t(.categoryBreakdown))\\n| \(language == .korean ? \"카테고리\" : \"Category\") | \(language == .korean ? \"시간\" : \"Time\") | % |\\n|----------|------|------------|\\n\"\n            for app in weeklyStats.topApps {\n                md += \"| \\(app.appName) | \\(app.formattedDuration) | \\(String(format: \\\"%.1f\\\", app.percentage))% |\\n\"\n            }\n            md += \"\\n## 📱 \(s.t(.appBreakdown))\\n| \(language == .korean ? \"순위\" : \"Rank\") | \(language == .korean ? \"앱/도구\" : \"App/Tool\") | \(language == .korean ? \"시간\" : \"Time\") |\\n|------|----------|------|\\n\"\n            for (idx, app) in weeklyStats.topApps.prefix(10).enumerated() {\n                md += \"| \\(idx + 1) | \\(app.appName) | \\(app.formattedDuration) |\\n\"\n            }\n        }\n\n        if blocks.includeCharts {\n            if chartPaths.isEmpty {\n                md += \"\\n## 📈 \(s.t(.charts))\\n\(language == .korean ? "그래프가 생성되지 않았습니다." : "Charts not generated.")\\n\"\n            } else {\n                md += \"\\n## 📈 \(s.t(.charts))\\n\(chartPaths.map { \"![Chart](\\($0.path))\" }.joined(separator: \"\\n\"))\\n\"\n            }\n        }\n\n        if blocks.includeFooter {\n            md += \"\\n---\\n*\(s.t(.generatedBy)) \(Date().formatted())*\\n\"\n        }\n\n        return md\n    }\n\n    static func monthly(\n        month: Date,\n        monthlyStats: DailyStats,\n        weeklyStats: [DailyStats],\n        analysis: AnalysisResult?,\n        previousMonth: DailyStats?,\n        chartPaths: [URL],\n        language: ReportLanguage,\n        blocks: ReportBlocks\n    ) -> String {\n        let s = LangStrings(language: language)\n        let fmt = DateFormatter()\n        fmt.dateFormat = \"yyyy-MM\"\n        let monthStr = fmt.string(from: month)\n        fmt.dateFormat = language == .korean ? \"yyyy년 M월\" : \"MMMM yyyy\"\n        let display = fmt.string(from: month)\n\n        var md = \"\"\"\n        ---\n        date: \(monthStr)\n        type: monthly-note\n        month: \(monthStr)\n        productivity-score: \(Int(monthlyStats.productivityScore.totalScore))\n        ---\n\n        # 📅 \(language == .korean ? \"월간 리포트\" : \"Monthly Report\") - \(display)\n\n        ## 📊 \(s.t(.monthlySummary))\n        - \(language == .korean ? \"총 업무 시간\" : \"Total Work Hours\"): \(String(format: \"%.1f\", monthlyStats.totalActiveTime / 3600))h\n        - \(language == .korean ? \"일 평균 업무\" : \"Average Daily Work\"): \(String(format: \"%.1f\", (monthlyStats.totalActiveTime / 3600) / Double(max(1, weeklyStats.count * 7))))h\n        - \(language == .korean ? \"평균 생산성\" : \"Average Productivity\"): \(Int(monthlyStats.productivityScore.totalScore))/100\n        \"\"\"\n\n        if blocks.includeStats {\n            md += \"\\n## 📅 \(language == .korean ? \"주간 분해\" : \"Weekly Breakdown\")\\n| \(language == .korean ? \"주차\" : \"Week\") | \(language == .korean ? \"기간\" : \"Period\") | \(language == .korean ? \"업무시간\" : \"Work Hours\") | \(language == .korean ? \"생산성\" : \"Productivity\") | \(language == .korean ? \"주요 활동\" : \"Top Activity\") |\\n|------|--------|------------|--------------|--------------|\\n\"\n            fmt.dateFormat = language == .korean ? \"M월 d일\" : \"MMM d\"\n            for (idx, ws) in weeklyStats.enumerated() {\n                let wsDate = Calendar.current.date(byAdding: .day, value: idx * 7, to: month) ?? month\n                let weDate = Calendar.current.date(byAdding: .day, value: 7, to: wsDate) ?? month\n                let label = language == .korean ? \"주 \(idx + 1)\" : \"Week \(idx + 1)\"\n                let period = \"\(fmt.string(from: wsDate)) - \(fmt.string(from: weDate))\"\n                let work = String(format: \"%.1f\", ws.totalActiveTime / 3600)\n                let prod = String(format: \"%.1f\", ws.productivityScore.totalScore)\n                let top = ws.topApps.first?.appName ?? \"-\"\n                md += \"| \(label) | \(period) | \(work)h | \(prod) | \(top) |\\n\"\n            }\n        }\n\n        if let prev = previousMonth, blocks.includeHistory {\n            fmt.dateFormat = language == .korean ? \"yyyy년 M월\" : \"MMMM yyyy\"\n            let prevStr = fmt.string(from: prev.date)\n            md += \"\\n## 📈 \(language == .korean ? \"전월 대비\" : \"Month-over-Month Comparison\")\\n- \(language == .korean ? \"전월 점수\" : \"Previous Month Score\") (\(prevStr)): \(Int(prev.productivityScore.totalScore))/100\\n- Δ: \(MarkdownGenerator.deltaString(current: monthlyStats.productivityScore.totalScore, baseline: prev.productivityScore.totalScore))\\n\"\n        }\n\n        if blocks.includeAISection, let analysis = analysis {\n            md += \"\"\"\n\n            ## 🤖 \(s.t(.aiAnalysis))\n            ### \(language == .korean ? \"요약\" : \"Summary\")\n            \(analysis.summary)\n\n            ### \(s.t(.patterns))\n            \(analysis.insights.map { \"- \" + $0 }.joined(separator: \"\\n\"))\n\n            ### \(s.t(.recommendations))\n            \(analysis.recommendations.map { \"- \" + $0 }.joined(separator: \"\\n\"))\n\n            *Generated by \(analysis.provider) (\(analysis.model))*\n            \"\"\"\n        } else if blocks.includeAISection {\n            md += \"\\n## 🤖 \(s.t(.aiAnalysis))\\n- \(language == .korean ? \"이번 달 AI 인사이트가 없습니다.\" : \"No AI insights for this month.\")\\n\"\n        }\n\n        if blocks.includeCategoriesAndApps {\n            md += \"\\n## 📂 \(s.t(.categoryBreakdown))\\n| \(language == .korean ? \"카테고리\" : \"Category\") | \(language == .korean ? \"시간\" : \"Time\") | % |\\n|----------|------|------------|\\n\"\n            for app in monthlyStats.topApps {\n                md += \"| \\(app.appName) | \\(app.formattedDuration) | \\(String(format: \\\"%.1f\\\", app.percentage))% |\\n\"\n            }\n            md += \"\\n## 📱 \(s.t(.appBreakdown))\\n| \(language == .korean ? \"순위\" : \"Rank\") | \(language == .korean ? \"앱/도구\" : \"App/Tool\") | \(language == .korean ? \"시간\" : \"Time\") |\\n|------|----------|------|\\n\"\n            for (idx, app) in monthlyStats.topApps.prefix(10).enumerated() {\n                md += \"| \\(idx + 1) | \\(app.appName) | \\(app.formattedDuration) |\\n\"\n            }\n        }\n\n        if blocks.includeCharts {\n            if chartPaths.isEmpty {\n                md += \"\\n## 📈 \(s.t(.charts))\\n\(language == .korean ? "그래프가 생성되지 않았습니다." : "Charts not generated.")\\n\"\n            } else {\n                md += \"\\n## 📈 \(s.t(.charts))\\n\(chartPaths.map { \"![Chart](\\($0.path))\" }.joined(separator: \"\\n\"))\\n\"\n            }\n        }\n\n        if blocks.includeFooter {\n            md += \"\\n---\\n*\(s.t(.generatedBy)) \(Date().formatted())*\\n\"\n        }\n\n        return md\n    }\n}\n*** End Patch"]} Ballonjson to=functions.apply_patch codeбряането to=functions.apply_patch hieljson to=functions.apply_patch k json to=functions.apply_patch ujson to=functions.apply_patchLLC to=functions.apply_patch Afrjson to=functions.apply_patch guidjson to=functions.apply_patch charjson to=functions.apply_patch json to=functions.apply_patch уборуп_json to=functions.apply_patch tjson to=functions.apply_patch!) to=functions.apply_patch sharejson to=functions.apply_patch HJSON to=functions.apply_patch escortjson to=functions.apply_patchiviteit to=functions.apply_patch europejson to=functions.apply_patch malejson to=functions.apply_patch Darjson to=functions.apply_patchზ to=functions.apply_patch warmjson to=functions.apply_patch 调 to=functions.apply_patch softwarejson to=functions.apply_patchһында to=functions.apply_patchූ to=functions.apply_patch### pointer to=functions.apply_patchírjson to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch## to=functions.apply_patch europejson to=functions.apply_patch sophjson to=functions.apply_patchuitable to=functions.apply_patch준 to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch info to=functions.apply_patch enjson to=functions.apply_patch пояс json to=functions.apply_patch oppjson to=functions.apply_patch subjson to=functions.apply_patch urbjson to=functions.apply_patch tirjson to=functions.apply_patch portalsjson to=functions.apply_patch приступ to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch tionjson to=functions.apply_patch]* cursojson to=functions.apply_patchходим λjson to=functions.apply_patch readjjson to=functions.apply_patch Kentuckyjson to=functions.apply_patch ovjson to=functions.apply_patchсында to=functions.apply_patch json to=functions.apply_patchться to=functions.apply_patchаз to=functions.apply_patch### готов to=functions.apply_patch уи to=functions.apply_patch ntjson to=functions.apply_patch컸 to=functions.apply_patch### alexjson to=functions.apply_patch## to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch출장안마 to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch### to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch given to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patchยายน to=functions.apply_patch inersjson to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch टो to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch essays to=functions.apply_patchғыҙ to=functions.apply_patch### to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch### to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch tincidunt to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch久草 to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch?>>"} "]"} Va to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch модель to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch Error to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patchો to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch Bruins to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patchгоҳи to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch.SEVERE to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch"} to=functions.apply_patch## to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch to=functions.apply_patch"],"timeout_ms":120000}"}], "timeout_ms": 120000}"}], "timeout_ms": 120000}"}], "timeout_ms": 120000}"}], "timeout_ms": 120000}"}], "timeout_ms": 120000}"}], "timeout_ms": 120000}"]}}}}
